---
- name: Create certbot systemd drop in directory
  file:
    path: "/etc/systemd/system/certbot.service.d"
    state: directory
    mode: '0755'

- name: Create certbot systemd drop in
  template:
    src: "templates/systemd/hooks.conf"
    dest: "/etc/systemd/system/certbot.service.d/hooks.conf"
  notify: systemd daemon-reload
