---
- name: Create hook scripts
  template:
    src: "templates/hook.sh"
    dest: "/etc/letsencrypt/renewal-hooks/{{ item }}/hook.sh"
    mode: "u=rwx,g=rx,o=rx"
  with_items:
    - "pre"
    - "post"
    - "deploy"
